---
title: "Izar 2020 scRNAseq general plotting"
author: "Mike Cuoco"
output:
  html_document:
    theme: united
    df_print: kable
date: 'Compiled: `r format(Sys.Date(), "%B %d, %Y")`'
editor_options: 
  chunk_output_type: console
---
***

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  tidy = TRUE,
  tidy.opts = list(width.cutoff = 120),
  message = FALSE,
  warning = FALSE
)
knitr::opts_knit$set(root.dir = here::here())
```

```{r init}
library(tidyverse)
library(plyr)
library(reshape2)
library(Matrix)
library(Seurat)
# library(infercnv)
library(patchwork)
library(glue)
library(beepr)
library(broom)
library(here)
library(msigdbr)

# saving obj setup
proj = "Izar_2020"
date = Sys.Date()

# setup directories
if (!dir.exists(here("mike_plots",proj))){
  dir.create(here("mike_plots",proj))
  dir.create(here("mike_plots",proj,date))
} else if (!dir.exists(here("mike_plots",proj,date))){
  dir.create(here("mike_plots",proj,date))
}

fig.dir = here("mike_plots",proj,date)

# Signatures
ovca_sigs = read_csv("gene_lists/Ovarian_Signatures_combined.csv")[,1:26] %>% 
  as.list() %>%
  lapply(function(x) x[!is.na(x)])
hallmarks = read_lines("gene_lists/hallmarks.txt")
hall_sigs = msigdbr(species = "Homo sapiens", category = "H") %>% 
  filter(gs_name %in% hallmarks) %>% 
  select(gs_name, gene_symbol) %>% 
  dlply("gs_name", function(x) pull(x,gene_symbol))
# hall_sigs = msigdbr(species = "Homo sapiens") %>%
#   filter(gs_name %in% c("GO_RESPONSE_TO_ENDOPLASMIC_RETICULUM_STRESS","GO_REGULATION_OF_RESPONSE_TO_ENDOPLASMIC_RETICULUM_STRESS")) %>%
#   select(gs_name, gene_symbol) %>%
#   dlply("gs_name", function(x) pull(x,gene_symbol)) %>%
#   c(hall_sigs)
sigs = names(hall_sigs)

# Read in most recently processed Seurat objects
ovca_10x = list.files(here("data","Izar_2020"), full.names = T) %>% 
  grep("preproc",.,value=T) %>%
  grep("10x",.,value=T) %>%
  readRDS()
ovca_SS2 = list.files(here("data","Izar_2020"), full.names = T) %>% 
  grep("preproc",.,value=T) %>%
  grep("SS2",.,value=T) %>%
  readRDS()
ovca_PDX = list.files(here("data","Izar_2020"), full.names = T) %>% 
  grep("preproc",.,value=T) %>%
  grep("PDX",.,value=T) %>%
  readRDS()
```

### Generate summary table for each dataset

```{r summary tables}
# source custom function
source(here('mike_code','seurat_tab.R'))
# 10X dataset
ovca_10x$treatment.status = factor(x = ovca_10x$treatment.status, levels = c("Treatment-naïve","After 1 cycle of chemotherapy","On-treatment"))
seurat_tab(ovca_10x, col_var = "patient", row_var = "cell.type", group_var = "treatment.status", title = "# Cells per Patient by Treatment Status") %>%
  row_group_order(c("Treatment-naïve","After 1 cycle of chemotherapy","On-treatment")) %>%
  gtsave("10x_celltype_ts_tab.png", expand = 10, path = fig.dir)
subset(ovca_10x, subset = cell.type == "Malignant") %>%
  seurat_tab(col_var = "patient", row_var = "treatment.status", title = "# Malignant Cells per Patient by Treatment Status") %>%
  gtsave("10x_malig_ts_tab.png", expand = 10, path = fig.dir)

# SS2 dataset
ovca_SS2$Time = factor(x = ovca_SS2$Time , levels = c("0","1","2","3","4","5"))
ovca_SS2$treatment.status = factor(x = ovca_SS2$treatment.status , levels = c("Treatment-naïve","On-treatment"))
seurat_tab(ovca_SS2, col_var = "Patient", row_var = "cell.type", group_var = "treatment.status", title = "# Cells per Patient by Treatment Status") %>%
 gtsave("SS2_celltype_ts_tab.png", expand = 10, path = fig.dir)
subset(ovca_SS2, subset = cell.type == "Malignant") %>%
 seurat_tab(col_var = "Patient", row_var = "Time", group_var = "treatment.status", title = "# Malignant Cells per Patient by Treatment Status") %>%
 gtsave("SS2_malig_ts_tab.png", expand = 10, path = fig.dir)

# PDX dataset
ovca_PDX$treatment.status = factor(x = ovca_PDX$treatment.status , levels = c("vehicle","MRD","relapse"))
seurat_tab(ovca_PDX, col_var = "model_ID", row_var = "treatment.status", title = "#  Cells per Model by Treatment Status") %>%
 gtsave("PDX_ts_tab.png", expand = 10, path = fig.dir)
```

```{r pcaplot}

```

```{r umapplot, fig.height=5, fig.width=7}
list = list("10x" = list("ovca_10x" = ovca_10x,
                          "meta_features" = c("patient","sample.ID","time","clst",
                                              "seurat_clusters","Phase","cell.type","treatment.status")),
            "SS2" = list("ovca_SS2" = ovca_SS2,
                         "meta_features" = c("Patient","Time","clst",
                                             "seurat_clusters", "Phase","cell.type", "treatment.status")),
            "PDX" = list("ovca_PDX" = ovca_PDX,
                         "meta_features" = c("mouse_ID","model_ID",
                                             "treatment.status","Phase")))

for (j in 1:length(list)){
  p_list = vector(mode = "list",length = length(list[[j]][["meta_features"]]))
  names(p_list) = list[[j]][["meta_features"]]
  for (i in list[[j]][["meta_features"]]) {
   p_list[[i]] = DimPlot(object = list[[j]][[1]], reduction = 'umap', group.by = i) + 
     labs(color = i) +
    plot_annotation(glue("{gsub('_',' ',proj)} {names(list)[j]}: {ncol(list[[j]][[1]]@assays$RNA@scale.data)} cells {nrow(list[[j]][[1]]@assays$RNA@scale.data)} genes"), caption = date())
   ggsave(glue('{fig.dir}/{names(list)[j]}_umap_{i}.png'), width = 7, height = 7, plot = p_list[[i]])
   if (i == list[[j]][["meta_features"]][1]){plot = p_list[[i]]}
   else {plot = plot + p_list[[i]]}
  }
  ggsave(glue('{fig.dir}/{names(list)[j]}_umap_all-meta.png'),plot =plot, width = 15, height = 10)
}
```

# Plot all gene signatures 

```{r gene signatures}
# treatment versus gene signature for each dataset
## 10x
Idents(ovca_10x) <- "treatment.status"
ovca_10x@active.ident = factor(x = ovca_10x@active.ident , levels = c("Treatment-naïve","After 1 cycle of chemotherapy","On-treatment"))
p = DotPlot(subset(ovca_10x, subset = cell.type == "Malignant"), features = sigs) + coord_flip() + RotatedAxis()  + labs(title = "10X data", x = "Gene Signature", y = "Treatment Status") + theme(axis.text.y = element_text(size = 10))
ggsave(glue('{fig.dir}/10x_sigs_malig_ts_dot.png'),p,width = 10, height = 12) 
## PDX
Idents(ovca_PDX) <- "treatment.status"
ovca_PDX@active.ident = factor(x = ovca_PDX@active.ident , levels = c("vehicle","MRD","relapse"))
p = DotPlot(ovca_PDX, features = sigs) + coord_flip() + RotatedAxis() + labs(title = "PDX data", x = "Gene Signature", y = "Treatment Status")  + theme(axis.text.y = element_text(size = 10))
ggsave(glue('{fig.dir}/PDX_sigs_ts_dot.png'), p,width = 10, height = 12)
# SS2
Idents(ovca_SS2) <- "treatment.status"
ovca_SS2@active.ident = factor(x = ovca_SS2@active.ident , levels = c("Treatment-naïve","On-treatment"))
p = DotPlot(subset(ovca_SS2, subset = cell.type == "Malignant"), features = sigs) + coord_flip() + RotatedAxis() + labs(title = "SS2 data", x = "Gene Signature",  y = "Treatment Status") + theme(axis.text.y = element_text(size = 10))
ggsave(glue('{fig.dir}/SS2_sigs_malig_ts_dot.png'), p, width = 10, height = 12)
Idents(ovca_SS2) <- "Time"
ovca_SS2@active.ident = factor(x = ovca_SS2@active.ident , levels = c("0","1","2","3","4","5"))
p = DotPlot(subset(ovca_SS2, subset = cell.type == "Malignant"), features = sigs) + coord_flip() + RotatedAxis() + labs(title = "SS2 data", x = "Gene Signature", y = "Time of Collection") + theme(axis.text.y = element_text(size = 10))
ggsave(glue('{fig.dir}/SS2_sigs_malig_time_dot.png'), p, width = 10, height = 12)
beep(4)
```

