---
title: "GSE146026_Izar_HGSOC_ascites"
author: "Michael Cuoco"
date: "4/1/2020"
output: html_document
---
```{r, setup, include=FALSE}
# Load required libraries
library(tidyverse)
library(Matrix)
library(Seurat)
library(patchwork)
source('/Users/mcuoco/OneDrive/Work/Programming/scripting/pca_fns.20170522.R')
```

```{r load_dat}
base.out.dir = NULL # place holder
base.in.dir="/Volumes/jesslyn_ovca/data/GSE146026_Izar_HGSOC_ascites_10x_log"

ss.names = c("1976","3250","3250.1","3266","3281","3288","3288.1","3290")
ss.names = ss.names[!grepl("STOPPEDEARLY", ss.names)]
sample.names=ss.names; 
names(sample.names)=ss.names ## sample.names used in 10X directory
# cutoffs=list(list("umi"=c(1800,18050), "gene"=c(1050,4500)),
#              list("umi"=c(1800,19000), "gene"=c(1050,4450)),
#              list("umi"=c(3500,25000), "gene"=c(1550,5100)),
#              list("umi"=c(2250,16500), "gene"=c(1150,4400)),
#              list("umi"=c(1200,6400), "gene"=c(750,2650)),
#              list("umi"=c(1100,6400), "gene"=c(700,2650)))
# cutoffs=lapply(ss.names, function(x) {NULL}); names(cutoffs)=ss.names
#pdf(paste0(dir.out, "/histn.qc.pdf"),w=6,h=6)
expr.dat.all=NULL
```

```{r}
for (s in ss.names) {
  print(paste0("Reading sample: ",s))
  expr.dat=Read10X(data.dir=paste0(base.in.dir, "/", sample.names[s]))
  # expr.dat.Seurat=new("seurat", raw.data = expr.dat)
  # expr.dat.Seurat=Setup(expr.dat.Seurat, min.cells = 0, min.genes = 0, do.logNormalize = F, do.scale = F, do.center = F, project = "Last minute")
  print(dim(expr.dat)); head(colnames(expr.dat))
  colnames(expr.dat)=paste0(s, ".", colnames(expr.dat))
  print(head(colnames(expr.dat)))
  n.umis.per.cell=Matrix::colSums(expr.dat); print(summary(n.umis.per.cell))
  n.genes.per.cell=Matrix::colSums(expr.dat>0)
  print(head(n.genes.per.cell)); print(summary(n.genes.per.cell))
  ## use quantiles to set initial values -> update after examining distribution
  cutoffs[[s]]=list("umi"=round(quantile(n.umis.per.cell, probs=c(0.01, 0.99))),
                    "gene"=round(quantile(n.genes.per.cell, probs=c(0.01, 0.99)))); print(cutoffs[[s]])
  ## UMI
  quants=cutoffs[[s]][["umi"]]
  # cutoffs[["WT_PBS"]][["umi"]]=c(1600,11800)
  # cutoffs[["WT_HDM"]][["umi"]]=c(1550, 15000)
  # cutoffs[["KO_Nmur1_PBS"]][["umi"]]=c(1325,11400)
  # cutoffs[["KO_Nmur1_HDM"]][["umi"]]=c(1850,15500)
  p=plot.histn(n.umis.per.cell, cutoffs=cutoffs[[s]][["umi"]], log.sc=F, sample.name=s, type="UMIs", do.print=F) + 
    geom_vline(xintercept=quants, color="blue", linetype="dashed")
  print(p)
  p=plot.histn(n.umis.per.cell, cutoffs=cutoffs[[s]][["umi"]], log.sc=T, sample.name=s, type="UMIs", bins=ifelse(s=="KO_Nmur1_PBS",150,200)) + 
        geom_vline(xintercept=log2(quants), color="blue", linetype="dashed")
  print(p)
  # plot.histn(n.umis.per.cell, cutoffs=cutoffs[[s]][["umi"]], log.sc=T, sample.name=s, type="UMIs")
  
  ## Gene
  quants=cutoffs[[s]][["gene"]]
  # cutoffs[["WT_PBS"]][["gene"]]=c(825,3350)
  # cutoffs[["WT_HDM"]][["gene"]]=c(825,3950)
  # cutoffs[["KO_Nmur1_PBS"]][["gene"]]=c(800, 3300)
  # cutoffs[["KO_Nmur1_HDM"]][["gene"]]=c(900,3750)
  p=plot.histn(n.genes.per.cell, cutoffs=cutoffs[[s]][["gene"]], log.sc=F, sample.name=s, type="Genes") + 
    geom_vline(xintercept=quants, color="blue", linetype="dashed")
  print(p)
  p=plot.histn(n.genes.per.cell, cutoffs=cutoffs[[s]][["gene"]], log.sc=T, sample.name=s, type="Genes", bins=ifelse(s=="KO_Nmur1_PBS",150,200)) +          
    geom_vline(xintercept=log2(quants), color="blue", linetype="dashed")
  print(p)
    
  # plot.histn(n.genes.per.cell, cutoffs=cutoffs[[s]][["gene"]], log.sc=T, sample.name=s, type="Genes")
  ## Gene x UMI
  cells2keep=plot.umi.v.gene(n.umis.per.cell, n.genes.per.cell, umi.cutoffs=cutoffs[[s]][["umi"]], 
                             gene.cutoffs=cutoffs[[s]][["gene"]], sample.name=s)
  ## saving
  write.table(data.frame(cells2keep), file=paste0(dir.out, "/", s, ".cells_kept.txt"), quote=F, col.names=F)
  expr.dat=expr.dat[,cells2keep]
  saveRDS(expr.dat, file=paste0(dir.out, "/", s, ".cnts_qc_init.RDS"))
  # n.genes.per.cell=colSums(counts>0)
  if (is.null(expr.dat.all)) {
    expr.dat.all=expr.dat
  } else {
    expr.dat.all=cbind(expr.dat.all, expr.dat)
  }
  print(dim(expr.dat.all))
  unique(sapply(colnames(expr.dat.all), function(x) {unlist(strsplit(x, ".", fixed=T))[1]}))
}
```