# R packages --------------------------------------------------------------
if (!require(pacman)) install.packages("pacman"); library(pacman)

p_load(tidyverse)
p_load(readxl)
p_load(plyr)
p_load(reshape2)
p_load(Matrix)
p_load(Seurat)
p_load(infercnv)
p_load(patchwork)
p_load(glue)
p_load(beepr)
p_load(broom)
p_load(gt)
p_load(msigdbr)
p_load(here)
p_load(fgsea)
p_load(GGally)
p_load(ggpubr)
p_load_gh("immunogenomics/presto")

source(here('mike_code','DotPlot2.R'))
#source(here('mike_code','DotPlot3.R'))
source(here('jesslyn_code','DEAnalysis_code.R'))
source(here('jesslyn_code','GSEA_code.R'))
source(here('mike_code','seurat_tab.R'))
