---
title: "Izar 2020 scRNAseq data preprocessing"
author: "Mike Cuoco"
output:
  html_document:
    theme: united
    df_print: kable
date: 'Compiled: `r format(Sys.Date(), "%B %d, %Y")`'
editor_options: 
  chunk_output_type: console
---
***

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  tidy = TRUE,
  tidy.opts = list(width.cutoff = 120),
  message = FALSE,
  warning = FALSE
)
knitr::opts_knit$set(root.dir = here::here())
set.seed(1)
source(here('packages.R'))
```

```{r init}
# saving obj setup
proj = "Izar_2020"
date = Sys.Date()

# setup directories
if (!dir.exists(here("mike_plots",proj))){
  dir.create(here("mike_plots",proj))
  dir.create(here("mike_plots",proj,date))
} else if (!dir.exists(here("mike_plots",proj,date))){
  dir.create(here("mike_plots",proj,date))
}

fig.dir = here("mike_plots",proj,date)

# read in gene lists and supp tables
hkgenes = read_lines("gene_lists/tirosh_house_keeping.txt", skip = 2)
ccgenes = read_lines("gene_lists/regev_lab_cell_cycle_genes.txt")
s.genes <- ccgenes[1:43]
g2m.genes <- ccgenes[44:97]
ovca_sigs = read_csv("gene_lists/Ovarian_Signatures_combined.csv")[,1:26] %>% 
  as.list() %>%
  lapply(function(x) x[!is.na(x)])

hallmarks = read_lines("gene_lists/hallmarks.txt")
hall_sigs = msigdbr(species = "Homo sapiens", category = "H") %>% 
  filter(gs_name %in% hallmarks) %>% 
  select(gs_name, gene_symbol) %>% 
  dlply("gs_name", function(x) pull(x,gene_symbol))
# hall_sigs = msigdbr(species = "Homo sapiens") %>% 
#   filter(gs_name %in% c("GO_RESPONSE_TO_ENDOPLASMIC_RETICULUM_STRESS","GO_REGULATION_OF_RESPONSE_TO_ENDOPLASMIC_RETICULUM_STRESS")) %>% 
#   select(gs_name, gene_symbol) %>% 
#   dlply("gs_name", function(x) pull(x,gene_symbol)) %>%
#   c(hall_sigs)

# Read in Seurat objects
ovca_10x = here("data",proj,"Izar_2020_10x.RDS") %>% readRDS()
ovca_SS2 = here("data",proj,"Izar_2020_SS2.RDS") %>% readRDS()
ovca_PDX = here("data",proj,"Izar_2020_PDX.RDS") %>% readRDS()
```

```{r get dims}
# Turn this into a table:
con <- file(glue("{fig.dir}/cells_genes_set.log"), open = "wt")
sink(con, split = T, append = F)
for (i in list("10x" = ovca_10x, "SS2" = ovca_SS2, "PDX" = ovca_PDX)){
  print(i@project.name)
  print(glue("{dim(i)[1]} genes"))
  print(glue("{dim(i)[2]} cells"))
}
```

```{r check dist}
# distribution plots
cells = data.frame()
genes = data.frame()
features = data.frame()
expr = data.frame()
for (i in list("10x" = ovca_10x, "SS2" = ovca_SS2, "PDX" = ovca_PDX)){
  x = Matrix::colMeans(i[["RNA"]]) %>% as.data.frame()
  x$dataset = i@project.name
  cells = rbind(cells, x)
  y = Matrix::rowMeans(i[["RNA"]]) %>% as.data.frame()
  y$dataset = i@project.name
  genes = rbind(genes, y)
  z = select(i@meta.data, c("orig.ident","nCount_RNA","nFeature_RNA"))
  z$dataset = i@project.name
  features = rbind(features, z)
  w = as.vector(i@assays$RNA@data) %>% as.data.frame()
  w$dataset = i@project.name
  expr = rbind(expr, w)
}

p1 = ggplot(cells, aes(x = dataset, y = . , fill = dataset)) + 
  geom_violin() +
  labs(x = "cells",
       y = "avg expression") +
  theme_classic()

p2 = ggplot(genes, aes(x = dataset, y = . , fill = dataset)) + 
  geom_violin() +
  labs(x = "genes",
       y = "avg expresion") +
  theme_classic()

# p3 = ggplot(expr, aes(x = dataset, y = . , fill = dataset)) + 
#   geom_violin() +
#   labs(x = "all",
#        y = "expresion") +
#   theme_classic()

p = (p1 + p2) + plot_layout(guides = "collect") +
  plot_annotation(title = glue('{proj}: mean expression across cells and genes'),
                  caption = date())
ggsave(glue('{fig.dir}/summary_dist.png'),p, height = 7, width = 9)

p1 = ggplot(features, aes(x = orig.ident, y = nFeature_RNA, fill = orig.ident)) + 
  geom_violin() + 
  labs(y = "Genes") +
  theme_classic()

p2 = ggplot(features, aes(x = orig.ident, y = nCount_RNA, fill = orig.ident)) + 
  geom_violin() + 
  labs(y = "Counts") +
  theme_classic()

p = (p1 + p2) + plot_layout(guides = "collect") +
  plot_annotation(title = glue('{proj}: Genes/Counts per cell'),
                  caption = date())
ggsave(glue('{fig.dir}/genes_UMIs.png'), p, height = 7, width = 9)
```

```{r scale}
# do not scale or center data, already done by authors
ovca_10x = ScaleData(ovca_10x, do.scale = F, do.center = T)
ovca_SS2 = ScaleData(ovca_SS2, do.scale = F, do.center = T)
ovca_PDX = ScaleData(ovca_PDX, do.scale = F, do.center = T)
```

```{r pca,results='hide'}
# run PCA
ovca_10x <- RunPCA(object = ovca_10x, features = rownames(ovca_10x[["RNA"]]@data))
ovca_SS2 <- RunPCA(object = ovca_SS2, features = rownames(ovca_SS2[["RNA"]]@data))
ovca_PDX <- RunPCA(object = ovca_PDX, features = rownames(ovca_SS2[["RNA"]]@data))

# save plots, color by Genes and Counts
FeaturePlot(ovca_10x, reduction = "pca", features = c("nFeature_RNA","nCount_RNA")) %>%
     ggsave(glue('{fig.dir}/ovca_10x_pca.png'), width = 14, height = 7, plot = .)
FeaturePlot(ovca_SS2, reduction = "pca", features = c("nFeature_RNA","nCount_RNA")) %>%
     ggsave(glue('{fig.dir}/ovca_SS2_pca.png'), width = 14, height = 7, plot = .)
FeaturePlot(ovca_PDX, reduction = "pca", features = c("nFeature_RNA","nCount_RNA")) %>%
     ggsave(glue('{fig.dir}/ovca_PDX_pca.png'), width = 14, height = 7, plot = .)
```

```{r cluster, fig.height=5, fig.width=7}
ovca_10x <- FindNeighbors(object = ovca_10x, dims = 1:10)
ovca_10x <- FindClusters(object = ovca_10x, resolution = 0.5)

# Look at cluster IDs of the first 5 cells
head(x = Idents(object = ovca_10x), 5)

ovca_SS2 <- FindNeighbors(object = ovca_SS2, dims = 1:10)
ovca_SS2 <- FindClusters(object = ovca_SS2, resolution = 0.5)

# Look at cluster IDs of the first 5 cells
head(x = Idents(object = ovca_SS2), 5)

ovca_PDX <- FindNeighbors(object = ovca_PDX, dims = 1:10)
ovca_PDX <- FindClusters(object = ovca_PDX, resolution = 0.5)

# Look at cluster IDs of the first 5 cells
head(x = Idents(object = ovca_PDX), 5)
```

### Run non-linear dimensional reduction (UMAP/tSNE)

```{r tsne, fig.height=5, fig.width=7}
ovca_10x <- RunUMAP(object = ovca_10x, dims = 1:10)
ovca_SS2 <- RunUMAP(object = ovca_SS2, dims = 1:10)
ovca_PDX <- RunUMAP(object = ovca_PDX, dims = 1:10)
```

```{r cell cycle}
ovca_10x <- CellCycleScoring(ovca_10x, s.features = s.genes, g2m.features = g2m.genes)
ovca_SS2 <- CellCycleScoring(ovca_SS2, s.features = s.genes, g2m.features = g2m.genes)
ovca_PDX <- CellCycleScoring(ovca_PDX, s.features = s.genes, g2m.features = g2m.genes)
```

```{r add sigs}
sigs = hall_sigs
col = ncol(ovca_10x@meta.data)
ovca_10x = AddModuleScore(ovca_10x, features = sigs, name = names(sigs), nbin = 50, search = T)
names(ovca_10x@meta.data)[(col+1):ncol(ovca_10x@meta.data)] = names(sigs)

col = ncol(ovca_SS2@meta.data)
ovca_SS2 = AddModuleScore(ovca_SS2, features = sigs, name = names(sigs), nbin = 50, search = T)
names(ovca_SS2@meta.data)[(col+1):ncol(ovca_SS2@meta.data)] = names(sigs)

col = ncol(ovca_PDX@meta.data)
ovca_PDX = AddModuleScore(ovca_PDX, features = sigs, name = names(sigs), nbin = 50, search = T)
names(ovca_PDX@meta.data)[(col+1):ncol(ovca_PDX@meta.data)] = names(sigs)
```

```{r saveobject}
saveRDS(ovca_10x, here("data",proj,glue("10x_preproc_MC.RDS")))
saveRDS(ovca_SS2, here("data",proj,glue("SS2_preproc_MC.RDS")))
saveRDS(ovca_PDX, here("data",proj,glue("PDX_preproc_MC.RDS")))
beep(4)
```

