---
title: "Normalization Testing"
author: "Michael Cuoco"
date: "6/4/2020"
output:
  html_document:
    theme: united
    df_print: kable
date: 'Compiled: `r format(Sys.Date(), "%B %d, %Y")`'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  tidy = TRUE,
  tidy.opts = list(width.cutoff = 120),
  message = FALSE,
  warning = FALSE
)
knitr::opts_knit$set(root.dir = here::here())
```

```{r init}
library(tidyverse)
library(plyr)
library(reshape2)
library(Matrix)
library(Seurat)
library(patchwork)
library(glue)
library(gt)
library(beepr)
library(broom)
library(here)
library(msigdbr)
library(presto)
library(fgsea)
source(here('jesslyn_code','GSEA_code.R'))

# saving obj setup
proj = "Izar_2020"
date = Sys.Date()

# setup directories
if (!dir.exists(here("mike_plots",proj))){
  dir.create(here("mike_plots",proj))
  dir.create(here("mike_plots",proj,date))
} else if (!dir.exists(here("mike_plots",proj,date))){
  dir.create(here("mike_plots",proj,date))
}

fig.dir = here("mike_plots",proj,date)

# Signatures
ovca_sigs = read_csv("gene_lists/Ovarian_Signatures_combined.csv")[,1:26] %>% 
  as.list() %>%
  lapply(function(x) x[!is.na(x)])
hallmarks = read_lines("gene_lists/hallmarks.txt")
hall_sigs = msigdbr(species = "Homo sapiens", category = "H") %>% 
  filter(gs_name %in% hallmarks) %>% 
  select(gs_name, gene_symbol) %>% 
  dlply("gs_name", function(x) pull(x,gene_symbol))
# hall_sigs = msigdbr(species = "Homo sapiens") %>%
#   filter(gs_name %in% c("GO_RESPONSE_TO_ENDOPLASMIC_RETICULUM_STRESS","GO_REGULATION_OF_RESPONSE_TO_ENDOPLASMIC_RETICULUM_STRESS")) %>%
#   select(gs_name, gene_symbol) %>%
#   dlply("gs_name", function(x) pull(x,gene_symbol)) %>%
#   c(hall_sigs)
sigs = names(hall_sigs)

# Read in processed SS2 and PDX Seurat objects
ovca_SS2 = list.files(here("data","Izar_2020"), full.names = T) %>% 
  grep("preproc",.,value=T) %>%
  grep("SS2",.,value=T) %>%
  readRDS()
ovca_PDX = list.files(here("data","Izar_2020"), full.names = T) %>% 
  grep("preproc",.,value=T) %>%
  grep("PDX",.,value=T) %>%
  readRDS()
```

```{r}
# Dot Plots
Idents(ovca_PDX) <- "treatment.status"

##  DotPlot with ln(), scaling, and centering
p1 = Seurat::DotPlot(ovca_PDX, features = names(hall_sigs)) + coord_flip() + RotatedAxis()  + 
  labs(title = "ln() + scaling + centering", x = "Gene Signature", y = "Treatment Status") + 
  theme(axis.text.y = element_text(size = 10))
ggsave(glue('{fig.dir}/dot-test_PDX_full.png'),p1,width = 10, height = 12) 
##  DotPlot with ln() + log10()
p2 = Seurat::DotPlot(ovca_PDX, features = names(hall_sigs), scale = F) + coord_flip() + RotatedAxis()  + 
  labs(title = "ln() + log10()", x = "Gene Signature", y = "Treatment Status") + 
  theme(axis.text.y = element_text(size = 10))
ggsave(glue('{fig.dir}/dot-test_PDX_ln-log10.png'),p2,width = 10, height = 12) 

## DotPlot with ln() only
data.plot = FetchData(ovca_PDX, c(names(hall_sigs),"treatment.status")) %>% reshape2::melt(variable.name = "ident")
data.plot = ddply(data.plot, c("treatment.status","ident"), function(data.use) {
          x = data.use$value
          data.frame(avg.exp = mean(x = expm1(x = x)), pct.exp = length(x = x[x > 0]) / length(x = x))
          })

p3 = ggplot(data = data.plot, mapping = aes_string(x = "treatment.status", y = "ident")) + 
     geom_point(mapping = aes_string(size = "pct.exp", color = "avg.exp")) + 
     theme(axis.title.x = element_blank(), axis.title.y = element_blank()) + 
     guides(size = guide_legend(title = "Percent Expressed"),
            color = guide_colorbar(title = 'Average Expression')) + 
     scale_size_continuous(range = c(0, 6), limits = c(0,1), labels = scales::percent) +
     scale_color_gradient(low = "lightgrey", high = "blue") +
     labs(title = "ln() only", x = "Gene Signature", y = "Treatment Status") + 
     theme_classic()
ggsave(glue('{fig.dir}/dot-test_PDX_ln.png'),p3,width = 10, height = 12) 

## DotPlot withuot any transformations
data.plot = FetchData(ovca_PDX, c(names(hall_sigs),"treatment.status")) %>% reshape2::melt(variable.name = "ident")
data.plot = ddply(data.plot, c("treatment.status","ident"), function(data.use) {
          x = data.use$value
          data.frame(avg.exp = mean(x), pct.exp = length(x = x[x > 0]) / length(x = x))
          })

p4 = ggplot(data = data.plot, mapping = aes_string(x = "treatment.status", y = "ident")) + 
     geom_point(mapping = aes_string(size = "pct.exp", color = "avg.exp")) + 
     theme(axis.title.x = element_blank(), axis.title.y = element_blank()) + 
     guides(size = guide_legend(title = "Percent Expressed"),
            color = guide_colorbar(title = 'Average Expression')) + 
     scale_size_continuous(range = c(0, 6), limits = c(0,1), labels = scales::percent) +
     scale_color_gradient(low = "lightgrey", high = "blue") +
     labs(title = "no transform", x = "Gene Signature", y = "Treatment Status") + 
     theme_classic()
ggsave(glue('{fig.dir}/dot-test_PDX_none.png'),p4,width = 10, height = 12) 

plots = list(p1,p2,p3,p4)
plot = p1+p2+p3+p4 + plot_layout(ncol = 4)
ggsave(glue('{fig.dir}/dot-test_PDX_comb.png'),plot,width = 30, height = 12)

```
