---
title: "HTAPP Data Processing (QC)"
author: "Jesslyn Goh and Mike Cuoco"
date: "6/3/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = here::here())
knitr::opts_chunk$set(echo = TRUE)
```

```{r init}
# Load packages
source(here::here('packages.R'))

# Read in Seurat objects
TST = readRDS(file = "data/HTAPP/jesslyn_TST_prepoc.RDS")

freshCD45neg = readRDS(file = "data/HTAPP/jesslyn_freshCD45neg_preproc.RDS")

fresh2 = readRDS(file = "data/HTAPP/jesslyn_fresh2_preproc.RDS")

```

```{r Metadata Metrics}
#VlnPlot of nUMI, nCount_RNA, nFeature_RNA, nGene, nReads, and percent_mito. 

Seurat_objects <- c(TST, freshCD45neg, fresh2)
names <- c("TST", "freshCD45neg", "fresh2")
index = 1
for (obj in Seurat_objects){
plot = VlnPlot(obj, features = c("nFeature_RNA", "nCount_RNA", "nUMI", "nGene", "nReads", "percent_mito"), pt.size = 0.5, combine = F)

name <- names[index]

plot[[1]] = plot[[1]] + labs(title = paste(name, "Raw nFeature_RNA"))
plot[[2]] = plot[[2]] + labs(title = paste(name, "Raw nCount_RNA"))
plot[[3]] = plot[[3]] + labs(title = paste(name, "Raw nUMI"))
plot[[4]] = plot[[4]] + labs(title = paste(name, "Raw nGene"))
plot[[5]] = plot[[5]] + labs(title = paste(name,"Raw nReads"))
plot[[6]] = plot[[6]] + ylim(-0.2, 0.5) + labs(title = paste(name,"Raw percent mito"))

plot[[1]] + plot[[2]] + plot_layout(guides = 'collect') #nFeature vs nCount
ggsave(glue("{name}_nFeatureVSnCount.png"), path = "jesslyn_plots/HTAPP", width = 10, height = 8)

plot[[2]] +plot[[3]] + plot[[5]]  + plot_layout(guides = 'collect') #nCount vs. nUMI vs. nReads
ggsave(glue("{name}_nCount_nUMI_nReads.png"), path = "jesslyn_plots/HTAPP", width = 10, height = 8)

plot[[1]] + plot[[4]] + plot_layout(guides = 'collect') #nFeature vs nGene 
ggsave(glue("{name}_nFeatureVSnGene.png"), path = "jesslyn_plots/HTAPP", width = 10, height = 8)

plot[[6]] #percent_mito
ggsave(glue("{name}_percentMito.png"),plot[[6]], path = "jesslyn_plots/HTAPP")

index = index +1 
}

index = 1

```

```{r QC}
#examine how doublets or empty droplets were detected

index = 1
for (obj in Seurat_objects){
  name <- names[index]

  obj$doublet_or_empty = as.logical(obj$doublet + obj$emptydrop)
  
  ggplot(obj@meta.data, aes(x = nFeature_RNA, y = nCount_RNA, color = doublet_or_empty, alpha =0.5)) + geom_point() + labs(x = "nFeature", y = "nCount", title = paste(name, "nFeature and nCount Metrics of Low Quality Droplets"))
  
  ggsave(glue("{name}_nFeatureXnCountByDrop.png"), path = "jesslyn_plots/HTAPP")
  
  index = index +1 
}
index = 1
```

```{r metadata metrics}
#graph distribution of cell types 
seurat_tab(TST, col_var = "annotate", row_var = "Condition", title = "Number of cells per cell type for TST")

seurat_tab(freshCD45neg, col_var = "annotate", row_var = "Condition", title = "Number of cells per cell type for freshCD45neg")

seurat_tab(fresh2, col_var = "annotate", row_var = "Condition", title = "Number of cells per cell type for fresh2")

```
