---
title: "Izar 2020 SS2 DE Analysis"
author: "Jesslyn Goh"
date: "6/17/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = here::here())
knitr::opts_chunk$set(echo = TRUE)
set.seed(1)
```

```{r init}
# Load packages
source(here::here('packages.R'))

# Read in Seurat objects
SS2Malignant = readRDS(file = "data/Izar_2020/jesslyn_SS2Malignant_processed.RDS")

#load in a list of hallmark names that we are interested in 
hallmark_names = read_lines("gene_lists/hallmarks.txt")
#load updated hallmarks 
hallmark.list <- vector(mode = "list", length = length(hallmark_names))
names(hallmark.list) <- hallmark_names
for(hm in hallmark_names){
  file <- read_lines(glue("hallmarks/{hm}_updated.txt"), skip = 1)
  hallmark.list[[hm]] <- file
}
```

# DE ANALYSIS TYPE #1. FIND DIFFERENTIALLY EXPRESSED GENES FROM SCRATCH AND EVALUATE IF THEY MAKE UP A GO TERM COLLECTIVELY
````{r volcano plots}
#do separately for patient 8 and patient 9
genesets <- c("HALLMARK_OXIDATIVE_PHOSPHORYLATION", "HALLMARK_UNFOLDED_PROTEIN_RESPONSE")

for(patient in c(8,9)){
  #DE analysis between Treatment-naïve vs. On-treatment for each patient
  SS2_p <- subset(SS2Malignant, subset = (Patient == patient))
  
  #find DE genes
  DEgenes <- DEAnalysis_code(SS2_p, group.by= "treatment.status", group.1 = "Treatment-naïve", group.2 = "On-treatment")
  
  #feed in found DE genes as input to make volcano plots
  #graph all genes
  DEAnalysis_code(SS2_p, markers = DEgenes, group.by= "treatment.status", group.1 = "Treatment-naïve", group.2 = "On-treatment", graph = TRUE) + labs(title = glue("Patient {patient} Treatment-naive vs. On-treatment All DE Genes"))
    ggsave(glue("SS2_Patient{patient}_naiveVSontreatment_allDEGenes.png"), path= "jesslyn_plots/SS2/DE/Volcano", width = 15)
  
    #graph for specific genesets of interest
  for(geneset in genesets){
    #volcano plots with only oxphos genes (from all DE genes)
    DEAnalysis_code(SS2_p, markers = DEgenes, group.by = "treatment.status", group.1 = "Treatment-naïve", group.2 = "On-treatment", geneset = hallmark.list[[geneset]]) + labs(title = glue("Patient {patient} Treatment-naive vs. On-treatment DE Genes for {geneset}"))
    ggsave(glue("SS2_Patient{patient}_naiveVSontreatment_{geneset}DEGenes.png"), path= "jesslyn_plots/SS2/DE/Volcano", width = 15)  
  }
}
```

# DE ANALYSIS TYPE #2. GSEA - TEST DIFFERENTIAL EXPRESSION ON A PREDEFINED GO GENESET
```{r visualize DE}
#visualize DE of specified genesets 
#make Vln plots for patient 8 and 9 
sigs_of_interest <- c("HALLMARK_OXIDATIVE_PHOSPHORYLATION25", "HALLMARK_UNFOLDED_PROTEIN_RESPONSE33")
SS2p <- subset(SS2Malignant, subset = (Patient == c(8, 9)))
Idents(SS2p) <- "Patient"

plots <- VlnPlot(SS2p, features = sigs_of_interest, split.by = "treatment.status", combine = F)
plot_names <- c("Oxphos", "UTR")
for (i in c(1,2)){
  name <- plot_names[i]
  plots[[i]] <- plots[[i]] + labs(title = glue("{name} DE Between Treatment Conditions witin Each Patient"), x = "Patient", fill = "Treatment Status") + theme(plot.title = element_text(size = 6))
}
plots[[1]] + plots[[2]] + plot_layout(guides = 'collect')
ggsave("SS2_DE_VlnPlot.png", path = "jesslyn_plots/SS2/DE")
```

```{r paired GSEA}
#paired GSEA Treatment-naive vs. On-treatment within Patient 8 and Patient 9 
hallmarks_names <- names(hallmark.list)
GSEA.results <- vector("list", length = 2)
names(GSEA.results) <- c("8", "9")

for(patient in c("8","9")){
  SS2_p <- subset(SS2Malignant, subset = (Patient == patient))
  
  #run GSEA for each hallmark in hallmark.list for specific patient (treatment-naive vs. On-treatment)
  SS2_p.ranks <- GSEA_code(SS2_p, group.by = "treatment.status", hallmark.list, paired = TRUE, group.1 = "Treatment-naïve", group.2 = "On-treatment", ranks = NULL)
  GSEA.results[[patient]] <- GSEA_code(SS2_p, group.by = "treatment.status", hallmark.list, ranks = SS2_p.ranks) 
  
  #graph GSEA for each hallmark in hallmark.list 
  for(hallmark in hallmarks_names){
    plotEnrichment(hallmark.list[[hallmark]], SS2_p.ranks) + labs(title = glue("{hallmark} GSEA results for SS2 Patient {patient} Treatment-naive vs. On-treatment")) + theme(plot.title = element_text(size = 8))
    ggsave(glue("SS2_Patient{patient}_naiveVs.onTreatment_{hallmark}_GSEA.png"), path = glue( "jesslyn_plots/SS2/DE/GSEA_paired/Patient_{patient}"))
  }
}

#print results 
for(patient in c("8","9")){
  for(hm in c("HALLMARK_OXIDATIVE_PHOSPHORYLATION", "HALLMARK_UNFOLDED_PROTEIN_RESPONSE")){
    print(GSEA.results[[patient]] %>% filter(pathway == hm))
  }
}
```